# ======================
# FONT
# ======================
#font=JetBrainsMono Nerd Font:size=11
# fallback se non hai nerd font:
# font=monospace:size=10
font=JetBrainsMono:size=11
# ======================
# UI / LOOK
# ======================
pad=8x8
dpi-aware=yes

[main]
term=xterm-256color

# ======================
# COLORI (dark moderno)
# ======================
[colors-dark]
alpha=1
background=080808
#foreground=cdd6f4
foreground=ffffff

regular0=1e1e2e
regular1=f38ba8
regular2=a6e3a1
regular3=f9e2af
regular4=50a0ff
regular5=f5c2e7
regular6=94e2d5
regular7=bac2de

bright0=585b70
bright1=f38ba8
bright2=a6e3a1
bright3=f9e2af
bright4=89b4ff
bright5=f5c2e7
bright6=94e2d5
bright7=a6adc8

# ======================
# CURSORE
# ======================
[cursor]
style=beam
blink=yes

# ======================
# SCROLLBACK
# ======================
[scrollback]
lines=20000

# ======================
# MOUSE
# ======================
[mouse]
hide-when-typing=yes
