# ======================
# FONT
# ======================
#font=JetBrainsMono Nerd Font:size=11
# fallback se non hai nerd font:
# font=monospace:size=10
font=JetBrainsMono:size=10
# ======================
# UI / LOOK
# ======================
pad=8x8
dpi-aware=yes

[main]
term=xterm-256color

# ======================
# COLORI (dark moderno)
# ======================
[colors-dark]
foreground=ffffff
background=000000

## Normal/regular colors (color palette 0-7)
regular0=a8a8c0  # black
regular1=ff768e  # red
regular2=9ece6a  # green
regular3=e0af68  # yellow
regular4=7aa2f7  # blue
regular5=bb9af7  # magenta
regular6=7dcfff  # cyan
regular7=ffffff  # white

## Bright colors (color palette 8-15)
bright0=414868   # bright black
bright1=f7768e   # bright red
bright2=9ece6a   # bright green
bright3=e0af68   # bright yellow
bright4=7aa2f7   # bright blue
bright5=bb9af7   # bright magenta
bright6=7dcfff   # bright cyan
bright7=c0caf5   # bright white

## dimmed colors (see foot.ini(5) man page)
dim0=ff9e64
dim1=db4b4b
# ======================
# CURSORE
# ======================
[cursor]
style=beam
blink=yes

# ======================
# SCROLLBACK
# ======================
[scrollback]
lines=20000

# ======================
# MOUSE
# ======================
[mouse]
hide-when-typing=yes
